package com.example.demo.genres;

public enum Genre {
    ADVENTURE,
    ACTION,
    SPORTS,
    SIMULATION,
    PLATFORMER,
    RPG,
    FIRST_PERSON_SHOOTER,
    ACTION_ADVENTURE,
    FIGHTING,
    REAL_TIME_STRATEGY,
    RACING,
    SHOOTER,
    PUZZLE,
    CASUAL,
    STRATEGY_GAME,
    MMORPG,
    STEALTH,
    PARTY,
    ACTION_RPG,
    TACTICAL_ROLE_PLAYING,
    SURVIVAL,
    BATTLE_ROYALE
    }
